services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  flower:
    build: .
    command: /app/.venv/bin/celery -A app.internal.worker.celery_app flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
      worker:
        condition: service_started

  api:
    build: .
    container_name: torch_api
    command: /app/.venv/bin/fastapi run app/main.py --port 8000
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    container_name: torch_worker
    command: /app/.venv/bin/celery -A app.internal.worker.celery_app worker --loglevel=info --pool=solo
    environment:
      - REDIS_URL=redis://redis:6379/0
      - OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
    depends_on:
      - redis